ServerPort: 4541
GrpcPort: 4542
AppName: "ontology"
AppVersion: "0.0.1"
BaseUrl: "http://localhost:4441"
OtlpExporterUrl: ""
Environment: "local" # local, stg, production
Redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
  tls_enabled: false

Database:
  master_database_dsn: "postgres://kellyuser:kellypassword@localhost:5432/ontology?sslmode=disable"
  slave_database_dsn: "postgres://kellyuser:kellypassword@localhost:5432/ontology?sslmode=disable"

Notification:
  protocol: "grpc" # grpc, http 
  http_host: "http://localhost:4701"
  grpc_host: "localhost:4702"

FeatureFlag:
  audit_log: true

ClickHouse:
  enabled: true
  dsn: "tcp://clickhouse:clickhouse@localhost:9000/ontology?dial_timeout=5s&read_timeout=10s"

Agents:
  Ollama:
    url: "http://localhost:11434/api/generate"