// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/req_update_entity.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface RequestUpdateEntity {
  name: string;
  description: string;
  /** Not for FE to edit */
  code: string;
  display_order: number;
  is_start: boolean;
  is_terminal: boolean;
}
