// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_entities.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetEntities {
  code: string;
  message: string;
  data: ResponseGetEntities_Entity[];
  pagination: ResponseGetEntities_Pagination | undefined;
}

export interface ResponseGetEntities_Entity {
  id: string;
  feature_id: string;
  code: string;
  name: string;
  is_start: boolean;
  is_terminal: boolean;
  created_at: string;
}

export interface ResponseGetEntities_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
